PY = python3

test:
	PYTHONPATH=DRAMA-3.1.1/TOOLS/python_package $(PY) my_simulations/test/test.py

config:
	PYTHONPATH=DRAMA-3.1.1/TOOLS/python_package $(PY) my_simulations/config_modif/config_overview.py

sat_run: 
	PYTHONPATH=DRAMA-3.1.1/TOOLS/python_package $(PY) my_simulations/dpz_modif/sat_run.py

MC_run: 
	PYTHONPATH=DRAMA-3.1.1/TOOLS/python_package $(PY) my_simulations/MC_sim/MC_run.py

test_MC:
	PYTHONPATH=DRAMA-3.1.1/TOOLS/python_package $(PY) my_simulations/MC_sim/test_MC.py

full_sim:
	PYTHONPATH=DRAMA-3.1.1/TOOLS/python_package $(PY) my_simulations/full_sim/full_sim.py

visualisation:
	PYTHONPATH=DRAMA-3.1.1/TOOLS/python_package $(PY) my_simulations/visualisation/visualisation.py