#---<DRAMA/MIDAS/midas.plt>--------------------------<JoG/TUBS-ILR>-<01/2012>---
#    ######   ####     ##             #####   #####     ##    #    #    ##      
#    #       #        #  #            #    #  #    #   #  #   ##  ##   #  #     
#    #####    ####   ######   #####   #    #  #####   ######  # ## #  ######    
#    #            #  #    #           #    #  #    #  #    #  #    #  #    #    
#    ######  #####   #    #           #####   #    #  #    #  #    #  #    #    
#-------------------------------------------------------------------------------
#            ESA Debris Risk Assessment and Mitigation Analysis Tool            
#            MASTER-based Impact Flux and Damage Assessment Software
#-------------------------------------------------------------------------------
#                               DRAMA - MIDAS
#-------------------------------------------------------------------------------
# Note:  "midas.plt" contains the information required for the generation of the 
#        gnuplot driver files (*.gnu). For each spectra there will be a separate
#        driver file. Additional there is one driver file (nammed "[runid].gnu")
#        that contains a list of "load"-commands for all these driver files.
#-------------------------------------------------------------------------------
#
#===============================================================================
#
#--------------------------< General Plot Options >-----------------------------
# Note: Four lines are generated by default. They cover the three different data
#       types (Debris, Meteoroid, Clouds) and the overall result (Total).
#--------------------------------------:----------------------------------------
# Switch and line style for general line to plot
  1  1        Plot line for total of debris (except clouds)
  1  2        Plot line for total of meteoroids
  1  3        Plot line for total of clouds
  1  4        Plot line for total of sources (debris + meteoroids + clouds)
#
#-------------------------< Additional Plot Options >---------------------------
# Note:  The user has the option to see the results dependend on selected debris
#        and meteoroid sources. These additional plot options are deselected in 
#        the default settings.
#--------------------------------------:----------------------------------------
# Column 1    :  Switch (0=Off,1=On)
# Column 2    :  Line style
# Column 3-18 :  Select sources to be summarized within a single plot line
#                Switch (0=Off,1=On)
#                Column 3 =  explosion fragments
#                Column 4 =  collision fragments
#                Column 5 =  launch and mission related objects
#                Column 6 =  sodium potassium droplets
#                Column 7 =  solid rocket motor slag
#                Column 8 =  solid rocket motor dust
#                Column 9 =  paint flakes
#                Column 10 = ejecta
#                Column 11 = multi layer insulation (high area to mass ration)
#                Column 12 = debris cloud 1
#                Column 13 = debris cloud 2
#                Column 14 = debris cloud 3
#                Column 15 = debris cloud 4
#                Column 16 = debris cloud 5
#                Column 17 = meteoroid background
#                Column 18 = meteoroid annual streams
# Column 19   :  Line title (CHAR*10)
#|-||--||-------------------------------||--Title--|
   0   5 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0   EXPL
   0   6 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0   COLL
   0   7 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0   LMRO
   0   8 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0   NAKD
   0   9 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0   SRMS
   0  10 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0   SRMD
   0  11 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0   PAFL
   0  12 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0   EJEC
   0  13 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0   MLI
   0  14 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0   CLD1
   0  15 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0   CLD2
   0  16 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0   CLD3
   0  17 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0   CLD4
   0  18 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0   CLD5
   0  19 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0   MTBG
   0  20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1   MTAS
#---eof-------------------------------------------------------------------eof---
