#-----------------------------------------------------------------------
#                                                                       
#                __/__/    __/_/__/    __/__/__/  _/__/_/               
#              __/   __/  __/    __/  __/        __/                    
#             __/__/__/  __/_/__/    __/__/      __/__/                 
#            __/   __/  __/    __/  __/             __/                 
#           __/   __/  __/     __/ __/__/__/  _/__/_/                   
#                                                                       
#       Debris Risk Assessment and Mitigation Analysis Tool Suite       
#      MASTER(-based) Assessment of Risk Event Statistics Software      
#                          (DRAMA-ARES v3.1.1)                          
#                                                                       
# ARES version:         3.1.1
# Build date:           23-Feb-21
# Platform:             x86_64-linux-gnu
# Compiler:             GNU Fortran (Debian 8.3.0-6) 8.3.0
#-----------------------------------------------------------------------
# This file was generated by the ARES tool on:                          
# 2025/04/16 at 17:13:18
#-----------------------------------------------------------------------
# Comment:                                                              
#   DRAMA                                                                                             
#   Assessment of Risk Event Statistics                                                               
#                                                                       
# ARES functionality                                                    
#  4: Required Propellant                                               
#                                                                       
# Analysis epoch (yyyy/mm/dd):                                          
# 2016/11/01
#                                                                       
# Target Orbit:                                                         
#   7162.0000000 - semi major axis / km                                                 
#       0.000082 - eccentricity                                                         
#      98.550000 - inclination / deg                                                    
#      70.170000 - right ascension of the ascending node / deg                          
#     171.300000 - argument of perigee / deg                                            
#                                                                       
# Objects considered:                                                   
# 0.10000000E-01 - Lower Threshold / m                                                  
#  100.00000     - Upper Threshold / m                                                  
#                                                                       
# Definition of radar equation                                          
# Radar wavelength / m: 0.300
# Branch 1: Dmin(h) =        0.320 x (h/    2000.000)^(  2.0000)
# Branch 2: Dmin(h) =        0.700 x (h/   36000.000)^( -0.5000)
#                                                                       
# Population clouds (1 -enabled, 0 -disabled):                          
# 0 - none                
# 0 - none                
# 0 - none                
# 0 - none                
# 0 - none                
#                                                                       
# Covariances used for analyses: CDM
#                                                                       
# Collision probability algorithm: Alfriend-Akella
#                                                                       
# Collision avoidance strategy:  Target collision probability
#                                                                       
# Engine name: Cold Gas
#                                                                       
# Engine specific impulse (s):    60.000000
#                                                                       
#-----------------------------------------------------------------------
#                                                                       
# title: Annual Collision Probability                                   
#                                                                       
#-----------------------------------------------------------------------
#                                                                       
# coltitle: ACP detected population                                     
# coltitle: ACP whole population                                        
# coltitle: Flux due to the detected population [1/km^2/yr]             
# coltitle: Flux due to the whole population [1/km^2/yr]                
#                                                                       
#-----------------------------------------------------------------------
#   ACP_d       ACP_w       Flux_d      Flux_w                          
#-----------------------------------------------------------------------
  0.3075E-04  0.3462E-04  0.2651E+02  0.3495E+03
#                                                                       
#---eof-----------------------------------------------------------eof---
